CREATE TABLE IF NOT EXISTS faq_sections (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) ,
    description text,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP

);