CREATE TABLE IF NOT EXISTS our_teams (
    id SERIAL PRIMARY KEY,
    name VARCHAR(150),
    role VARCHAR(150),
    path_photo VARCHAR(150),
    tagline text NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP

);